@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 05 19:54:31 +0900 2025
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_eyeriss_behav -key {Behavioral:sim_1:Functional:tb_eyeriss} -tclbatch tb_eyeriss.tcl -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_datapath_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_vector_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_GIN_BUS_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_array_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_top_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_GLB_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_Processing_Pass_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_TOP_ctrl_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_eyeriss_behav.wcfg -log simulate.log"
call xsim  tb_eyeriss_behav -key {Behavioral:sim_1:Functional:tb_eyeriss} -tclbatch tb_eyeriss.tcl -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_datapath_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_vector_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_GIN_BUS_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_array_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/eyeriss_0710.srcs/sim_1/imports/waveform/tb_PE_top_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_GLB_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_Processing_Pass_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_TOP_ctrl_behav.wcfg -view C:/LAB/Graduation_Project/eyeriss_0710/tb_eyeriss_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
